name: ci

on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  test_cloud:
    name: test dynamodb cloud
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      TABLE_NAME: testing_table
    steps:
      - name: clone repo
        uses: actions/checkout@v1.0.0
      - name: install deno
        uses: denolib/setup-deno@v1.1.0
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: run tests
        run: deno run --allow-env --allow-read=$HOME/.aws --allow-net ./test/cloud.ts